# Generated by Django 2.2 on 2021-02-02 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailitem',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderDetail'),
        ),
    ]
