# Generated by Django 2.2 on 2021-06-12 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
        ('order', '0005_auto_20210205_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.DiscountType'),
        ),
    ]
