# Generated by Django 2.2 on 2021-06-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
    ]
